src/Entity/User.php
<?php

namespace App\Entity;


use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'security_user')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User extends AbstractEntity implements UserInterface, PasswordAuthenticatedUserInterface
{

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private string $password;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?UserInformation $userInformation = null;


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getUserInformation(): ?UserInformation
    {
        return $this->userInformation;
    }

    public function setUserInformation(UserInformation $userInformation): self
    {
        $this->userInformation = $userInformation;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{{ (site_meta_title_name is defined ? (site_meta_title_name |trans) ~ " | " : "") ~ "The Property" }}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('image/logo/logo.png') }}">
    {% block stylesheets %}
        {{ encore_entry_link_tags('css/app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('js/app') }}
    {% endblock %}

    {% block pageCss %}

    {% endblock %}

    {% block pageJs %}

    {% endblock %}
</head>
<body>
{% block body%}
    <!-- Top bar Start -->
    <header class="section-header border-y">
        <div class="container-fluid bg-primary text-white d-none d-lg-flex">
            <div class="container py-3">
                <div class="d-flex align-items-center">
                    <h2 class="text-white fw-bold m-0">Property</h2>
                    <div class="ms-auto d-flex align-items-center">
                        <a href="https://www.google.com/maps/search/?api=1&query=123+Main+St,+Anytown,+USA" target="_blank" class="text-white">
                            <small class="ms-4">
                                <i class="fa fa-map-marker-alt me-3"></i>123 Main St, Anytown, USA
                            </small>
                        </a>
                        <a href="mailto:info@example.com" class="text-white"><small class="ms-4"><i class="fa fa-envelope me-3"></i>info@example.com</small></a>
                        <a href="tel:+012 345 67890" class="text-white"><small class="ms-4"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</small></a>
                        <div class="ms-3 d-flex">
                            <a class="btn btn-sm-square btn-light text-primary rounded-circle ms-2" href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="btn btn-sm-square btn-light text-primary rounded-circle ms-2" href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="btn btn-sm-square btn-light text-primary rounded-circle ms-2" href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Top bar End -->

    <!-- Navbar Start -->
    <div class="container-fluid bg-white sticky-top">
        <div class="container">
            <nav class="navbar navbar-expand-lg bg-white navbar-light p-lg-0">
                <div class="d-flex align-items-center">
                    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                {#        small screen show user profile  we can hide with  class d-lg-none      #}
                {% if is_granted('ROLE_USER') %}
                    <button class="btn d-lg-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#rightSidebar" aria-controls="offcanvasRight">
                        {% if is_granted('ROLE_USER') and app.session.get('gender') == 'male' or is_granted('ROLE_USER') and app.session.get('gender') == 'female' or is_granted('ROLE_USER') and app.session.get('gender') == 'other' %}
                            {% if  app.session.get('userImage') %}
                                <img src="{{ asset('image/userImages/' ~ app.session.get('userImage') ) }}" id="profile" class="img-fluid img-thumbnail rounded-circle"
                                     alt="{{ app.session.get('userImage') }}"
                                     width="50">
                            {% else %}
                                <img src="{{ asset('image/userImage/' ~ app.session.get('gender') ~ '.png') }}" id="profile" class="img-fluid img-thumbnail rounded-circle"
                                     alt="{{ app.session.get('gender') ~'.png' }}" width="50">
                            {% endif %}
                        {% endif %}
                    </button>
                {% else %}
                    <div class="d-lg-none">
                        <a href="{{ path('login') }}" class="pe-1 d-lg-none"><i class="fa-solid fa-lock"></i> Login </a>
                        <a href="{{ path('register') }}" class="pe-1 d-lg-none">/ <i class="fa-solid fa-user-plus"></i> Register</a>
                    </div>
                {% endif %}

                <div class="collapse navbar-collapse ms-auto overflow-sm-auto" id="navbarCollapse">
                    {{ knp_menu_render('mainMenu') }}
                    {#        large screen show user profile we can hide with  class d-sm-none      #}
                    <div class="ms-auto d-sm-none">
                        {% if app.user %}
                            <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#rightSidebar" aria-controls="offcanvasRight">
                                {% if is_granted('ROLE_USER') and app.session.get('gender') == 'male' or is_granted('ROLE_USER') and app.session.get('gender') == 'female' or is_granted('ROLE_USER') and app.session.get('gender') == 'other' %}
                                    {% if  app.session.get('userImage') %}
                                        <img src="{{ asset('image/userImages/' ~ app.session.get('userImage') ) }}" id="profile" class="img-fluid img-thumbnail rounded-circle"
                                             alt="{{ app.session.get('userImage') }}"
                                             width="50">
                                    {% else %}
                                        <img src="{{ asset('image/userImage/'~ app.session.get('gender') ~ '.png') }}" id="profile" class="img-fluid img-thumbnail rounded-circle"
                                             alt="{{ app.session.get('gender') ~'.png' }}" width="50">
                                    {% endif %}
                                {% endif %}
                            </button>
                        {% else %}
                            <div class="d-sm-none">
                                <a href="{{ path('login') }}" class="pe-1 d-sm-none"> <i class="fa-solid fa-lock"></i> Login /</a>
                                <a href="{{ path('register') }}" class="pe-1 d-sm-none"> <i class="fa-solid fa-user-plus"></i> Register</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->

    <!-- Right  Navbar Start -->
    <div class="offcanvas offcanvas-end" tabindex="-1" id="rightSidebar" aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Property</h5>

            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 pb-3">
                <li>
                    <hr class="divider">
                </li>
                <li class="nav-item">
                    <a class="nav-link sideBarLinks" href="{{ path('account') }}" id="UserProfileNav">
                        <i class="fa-solid fa-user pe-1"></i> Account
                    </a>
                </li>
                <li>
                    <hr class="divider">
                </li>
                <li class="nav-item ">
                    <a class="nav-link sideBarLinks " href="{{ path('favouriteProperty') }}"> <i class="fa-solid fa-heart"></i> Favourite </a>
                </li>
                {% if is_granted('ROLE_AGENT') %}
                    <li>
                        <hr class="divider">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link sideBarLinks " href="{{ path('userProperty') }}"> <i class="fa-solid  fa-building pe-1"></i> Property </a>
                    </li>
                {% endif %}
                <li>
                    <hr class="divider">
                </li>
                <li class="nav-item ">
                    <a class="nav-link sideBarLinks " href="{{ path('logout') }}"> <i class="fa-solid fa-arrow-right-from-bracket pe-1"></i> Logout</a>
                </li>
                <li>
                    <hr class="divider">
                </li>
            </ul>
        </div>
    </div>
    <!-- Right  Navbar End -->

    {% block verifyEmail %}
        {% if app.user and  not app.user.verified %}
            <div class="container mt-5">
                <div class="card bg-primary">
                    <div class="card-body text-center">
                        <h1 class="text-white"> Welcome home {{ app.session.get('userName') }} ...</h1>
                        <h5>Please verified your email</h5>
                        <span class="text-white">{{ app.session.get('email') }}</span>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endblock %}

    <div class="container-fluid mt-5 {% block containerClass %}{% endblock %}">
        {% block pageContent %}{% endblock %}
    </div>


    {% block footer %}
        {{ include('navbar/footer.html.twig') }}
    {% endblock %}

{% endblock %}
</body>
</html>